# Generated by Django 4.1.7 on 2023-03-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Director Name', max_length=50)),
                ('description', models.TextField(help_text='About the Director', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title od the Movie', max_length=100)),
                ('summary', models.TextField(help_text='Put what this Book it is about', max_length=100)),
                ('director', models.ManyToManyField(to='film_app.director')),
            ],
        ),
    ]
